openapi: 3.0.2
info:
  version: 9dcb0dc8
  title: The SureVoIP RESTful API
  x-logo:
    url: 'https://www.surevoip.co.uk/sites/default/files/fbg_logo.png'
  description: >
    # Introduction

    Welcome to the SureVoIP RESTful hypermedia API (sometimes known as a VoIP
    REST API, Telecom REST API, SIP API, Hypermedia API or just VoIP API.)


    The SureVoIP API is a way for you to automate your interaction with the
    SureVoIP platforms. With the API, you can create your own scripts,
    applications or mashups which can:

    * List calls

    * create customers

    * search numbers

    * provision numbers

    * send SMS texts

    * create outbound calls

    * schedule announcements

    * schedule call hangups with an announcement

    * subscribe to events/alerts

    * track calls

    * retrieve invoices

    * grab your SIP details

    * check your IP address

    * be 100% self-sufficient

    * and much more!
  termsOfService: 'https://www.surevoip.co.uk/about/terms-conditions'
  contact:
    name: SureVoIP API Support
    email: support@surevoip.co.uk
    url: 'https://www.surevoip.co.uk/contact-surevoip'
servers:
  - url: 'https://api.surevoip.co.uk'
    description: Production SureVoIP API (live data)
  - url: 'https://sandbox.surevoip.co.uk'
    description: Sandbox SureVoIP API (data 24 hours old)
security:
  - BasicAuth: []
tags: []
externalDocs:
  description: SureVoIP API Wiki
  url: 'https://www.surevoip.co.uk/support/wiki/api_documentation'
